### ISSUE TITLE
Aquacontroller v1.3

### ISSUE THREAD

**Issue by digits1** [VTeselkin/AquaController2#1]
Вадим здравствуйте! Решил повторить проект aquacontroller v1.3, но столкнулся с проблемой такого характера. Не соединяется с wifi, а если соединяется, то не работает через приложение. Заметил такой момент, когда отключаешь RTC и включаешь устройство происходит соединение с сетью, подключаешь обратно, перезагружаешь опять беда. И ещё такой момент, когда происходит соединение перезагружаются часы которые собраны тоже на esp8266. Менял atmega328, прошивал с помощью TL866, менял esp8266, картина одна и та же. Подскажите в чём проблема, уже голову сломал. Спасибо, с уважением!

**Comment by VTeselkin** [comment]
Я так понимаю речь идет о старой версии контроллера еще на Arduino? Нужно больше вводных! Как собираете на плате или на макетной плате? Что значит не соединяется с WIFI? Вы можете зайти на 192.168.4.1 через браузер? В идеале нужно снять логи с устройства. Указать какая версия клиента и какая версия прошивки.

**Comment by digits1** [comment]
Да, совершенно верно старая версия. Плата версия 1.3, прошивка 1.3.9., брал от сюда:https://www.aquaforum.ua/showthread.php?t=232233 , клиент последняя версия с гугл плей. Подключался к точке доступа, заходил на 192.168.4.1. подключался к своей сети, делал всё как обычно при работе с esp8266. При первом включении всё ок, стоит перезагрузить и беда. Самое странное что часы перезагружаются которые подключены  к вай фай. Если можно я вам завтра напишу и лог отправлю. Ещё раз спасибо!

**Comment by VTeselkin** [comment]
Это читали: http://www.aquacontroller.ru/ru/main/class-layout/flasharduino В самом конце! Плата у вас тестолит или макетка? Что значит: часы которые подключены к вай фай?

**Comment by digits1** [comment]
Да, читал. Как я ни старался два коротких сигнала я так и не услышал. Плата стеклотекстолит из архива. У меня есть часы собранные на esp8266, происходит конфликт между устройствами. Если акваконтроллер подключается к сети, то часы перезагружаются, как это связано не пойму. Мак адреса разные.

**Comment by VTeselkin** [comment]
В момент первого запуска на i2c шине висит только экран?

**Comment by digits1** [comment]
Да

**Comment by VTeselkin** [comment]
И нет звука со спикера? На экране что-то есть при этом?

**Comment by digits1** [comment]
Вадим здравствуйте! Направил я вам лог и фото прикрепил. sergeyzaikin12@gmail.com

**Comment by VTeselkin** [comment]
Продублируйте тут. Не вижу вашего письма.

**Comment by digits1** [comment]
versions = 2.0.837UserID = eb570773e52c2981Create UDP Server!Start UDP Server!deviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}{"status":"success","message":"info","data":{"type":620}}Attempt to invoke virtual method 'int java.lang.String.length()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}192.168.0.170 : {"status":"success","message":"info","data":{"type":620}}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referenceRESULT_DATA_CORRUPTEDdeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referenceRESULT_DATA_CORRUPTEDdeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}{"status":"success","message":"info","data":{"type":622}}Attempt to invoke virtual method 'int java.lang.String.length()' on a null object referencedeviceInfo = null{"status":"get","message":"dev"}192.168.0.170 : {"status":"success","message":"info","data":{"type":622}}Attempt to invoke virtual method 'java.lang.Cloneable com.aerosoft.aquacontroller.Model.TaskResponse.TaskResponse.getResponse()' on a null object referenceRESULT_DATA_CORRUPTED

**Comment by VTeselkin** [comment]
Логи нужно было снять с устройства а не с телефона. По логу телефона вижу что вы не смогли получить даже начальный пакет deviceInfo. Нужно больше вводных. Помониторьте сеть на 8888 порту посмотрите шлет ли устройство вообще какие-то данные. Что у вас при этом на экране контроллера?  Кроме того что вы не можете подключится телефоном к устройству, какие проблемы именно с контроллером?

**Comment by digits1** [comment]
Ясно. На экране контроллера всё в порядке, работают таймеры. Хорошо попробую снять логи, но это уже наверное ни сегодня, на работе аврал был. Спасибо вам, извиняюсь за беспокойство.

**Comment by digits1** [comment]
Вадим, а резисторы R1, R2 на какой номинал должны быть? У меня стоят 4,7К, я вот подумал, может быть из-за них проблема, и возникает искажения сигнала по шине I2C.

**Comment by VTeselkin** [comment]
4.7k

**Comment by digits1** [comment]
Вадим добрый день! Вот что я наснимал.

NANO
ћ†`[1E][06]~[06][06]~fжш†`[18]`[1E]f~[1E]жаfx[1E]жш†`а†{"status":"success","message":"c_s","data":{"cl":[3,1,1,3,1,1,1,1],"c_t":[3,3,3,3,3,3,3,3]}}
{"status":"success","message":"c_s","data":{"cl":[3,1,1,3,1,1,1,1],"c_t":[3,3,3,3,3,3,3,3]}}
{"status":"success","message":"t_sen","data":{"t_se":[54,0,0,0]}}
{"status":"success","message":"t_sen","data":{"t_se":[55,0,0,0]}}

NANO

ћ†`[1E][06]~[06][06]~fжш†`[18]`[1E]f~[1E]жаfx[1E]жш†`а†{"status":"success","message":"c_s","data":{"cl":[3,1,1,3,1,1,1,1],"c_t":[3,3,3,3,3,3,3,3]}}
{"status":"success","message":"c_s","data":{"cl":[3,1,1,3,1,1,1,1],"c_t":[3,3,3,3,3,3,3,3]}}
{"status":"success","message":"set","NTP":1,"AUTO":1,"TIMERS":10,"SENSOR":4}
{"status":"success","message":"info","data":{"type":523}}
{"status":"success","message":"info","data":{"type":524}}
{"status":"success","message":"info","data":{"type":522}}
{"status":"success","message":"info","data":{"type":524}}
{"status":"success","message":"info","data":{"type":524}}
{"status":"success","message":"info","data":{"type":524}}
{"status":"success","message":"info","data":{"type":525}}
{"status":"success","message":"info","data":{"type":523}}
{"status":"success","message":"info","data":{"type":525}}
{"status":"success","message":"info","data":{"type":480}}
{"status":"success","message":"info","data":{"type":537}}
{"status":"success","message":"set","NTP":1,"AUTO":1,"TIMERS":10,"SENSOR":4}
{"status":"success","message":"info","data":{"type":524}}
{"status":"success","message":"info","data":{"type":525}}
{"status":"success","message":"t_sen","data":{"t_se":[56,0,0,0]}}
{"status":"success","message":"info","data":{"type":528}}
{"status":"success","message":"info","data":{"type":524}}
{"status":"success","message":"info","data":{"type":524}}


ESP12

{"status":"info","log":"WiFi:Init complete.."}
{"status":"get","message":"set"}
{"status":"info","log":"Couldn't get config "}
{"status":"info","log":"WiFi:Error...       "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Disable...     "}
{"status":"info","log":"WiFi:Load config... "}
{"status":"info","log":"WiFi:Try connect... "}
{"status":"info","log":"WAN:192.168.0.170   "}
{"status":"info","log":"NTP:Sending packet: "}
{"status":"info","log":"time2.google.com    "}
{"status":"post","message":"time_NTP","data":{"epoch":1678277966}}
{"status":"info","log":"NTP:Time update     "}
{"status":"info","log":"WAN:192.168.0.170   "}
{"status":"get","message":"t_sen"}
{"status":"info","log":"WAN:192.168.0.170   "}
{"status":"info","log":"WAN:192.168.0.170   "}
{"status":"info","log":"WAN:192.168.0.170   "}
{"status":"info","log":"WAN:192.168.0.170   "}
{"status":"info","log":"WAN:192.168.0.170   "}
{"status":"get","message":"t_sen"}
{"status":"info","log":"WAN:192.168.0.170   "}

**Comment by VTeselkin** [comment]
По логам все работает.
https://drive.google.com/file/d/1ZBCfytz7an6dBtLxSDrZwIEnJ7q0KRyL/view?usp=sharing  Попробуйте более старую версию приложения. Не уверен что последние версии поддерживают старый контроллер, они писались уже для версии 2.0
